version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  spring:
    container_name: spring
    image: ${DOCKERHUB_USERNAME}/jikgong
    depends_on:
      - redis
    volumes:
      - ./redis/data:/data
    environment:
      - DB_ENDPOINT=${DB_ENDPOINT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - FCM_PATH=${FCM_PATH}
    logging:
      driver: awslogs
      options:
        awslogs-group: "jikgong-logs"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "jikgong-stream"
    ports:
      - "8080:8080"
    restart: always

