version: "3.8"
services:
  jikgong-a:
    container_name: jikgong-a
    image: ${DOCKERHUB_USERNAME}/jikgong
    volumes:
      - ./logs:/logs
    env_file:
      - .env
#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: "jikgong-logs"
#        awslogs-region: "ap-northeast-2"
#        awslogs-stream: "jikgong-stream"
    ports:
      - "8080:8080"
    restart: always

networks:
  default:
    external:
      name: jikgongnet

