spring:
  profiles:
    active: ${environment}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_ENDPOINT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # 시작과 동시에 실행되는 것 방지

app:
  auth:
    secret-key: ${SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    s3:
      bucket: jikgong-image
      resize-bucket: jikgong-resize-bucket
    stack.auto: false #기본 cloudFormation 구성 시작 사용 x
    region:
      static: ap-northeast-2

#feign:
#  url:
#    sms-prefix: https://sens.apigw.ntruss.com
#  client:
#    default:
#      loggerLevel: FULL

# naver alimtalk
ncp:
  service-id: abc
  access-key: abc
  secret-key: abc
  plus-friend-id: abc

management:
  endpoints:
    web:
      base-path: /jikgong
      exposure:
        include: prometheus, health

fcm:
  path: ${FCM_PATH}

webhook:
  slack:
    url: ${WEBHOOK_SLACK_URL}