name: Java CI with Gradle

on:
  push:
    branches: [ "release" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/checkout@v3
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "jikgong-firebase.json"
          json: ${{ secrets.JIKGONG_FIREBASE }}
          dir: ./src/main/resources/firebase/

      - name: Run chmod to make graldew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar -Pspring.profiles.active=prod

      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jikgong .

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/jikgong

  cd-pipeline:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      # docker compose a 파일 scp
      - uses: actions/checkout@master
      - name: copy docker-compose.a.yml to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./docker-compose.a.yml"
          target: "/home/ubuntu/"

      # docker compose b 파일 scp
      - uses: actions/checkout@master
      - name: copy docker-compose.b.yml to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "./docker-compose.b.yml"
          target: "/home/ubuntu/"

#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ubuntu
#          password: ${{ secrets.SSH_PASSWORD }}
#          port: 22
#          script: |
#            sudo docker rm -f $(sudo docker ps -q -f "expose=8080")
#            sudo docker rm -f $(sudo docker ps -q -f "expose=6379")
#            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/jikgong
#            sudo docker-compose up -d
#            sudo docker image prune -f

      - name: Execute deploy.sh script remotely
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            chmod +x /home/ubuntu/deploy.sh
            /home/ubuntu/deploy.sh
